In [9]:
import torch

def combine_tensors(A, B):
    # 将A和B在最后一个维度上进行拼接
    C = torch.cat((A, B), dim=-1)
    C = torch.zeros_like(C)
    for i in range(C.shape[1]):
        if i % 2 == 0:
            C[:, i] = A[:, i//2]
        else:
            C[:, i] = B[:, i//2]
    return C

# 示例数据
batch_size = 3
input_dim = 4

# 创建示例张量A和B
A = torch.zeros(batch_size, input_dim)
B = torch.ones(batch_size, input_dim)

# 组合A和B
C = combine_tensors(A, B)

# 打印结果
print("A:", A.shape)
print(A)
print("B:", B.shape)
print(B)
print("C:", C.shape)
print(C)

A: torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
B: torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
C: torch.Size([3, 8])
tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0., 1.]])


In [4]:
C = torch.cat((A, B), dim=-1)


In [5]:
# 将C的最后一个维度进行重新排列
C.reshape(*C.shape[:-1], -1, 2)

tensor([[[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]]])

In [6]:
C = torch.zeros_like(C)

In [7]:
C

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
import torch

def expand_tensor(tensor, n):
    expanded_tensor = tensor.repeat(n, 1)
    return expanded_tensor

# 示例数据
tensor = torch.tensor([[1, 0]])  # 要扩展的张量
n = 5  # 扩展的次数

# 扩展张量
expanded_tensor = expand_tensor(tensor, n)

print("原始张量:")
print(tensor)
print("扩展后的张量:")
print(expanded_tensor)

原始张量:
tensor([[1, 0]])
扩展后的张量:
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]])


In [17]:
import torch
a = torch.tensor([[1, 1],[2, 0],[3, 0],[1, 0],[1, 0]],device='cuda')

In [25]:
for i,ai in enumerate(a):
    print(ai.nonzero(as_tuple=True)[0].tolist())

[0, 1]
[0]
[0]
[0]
[0]
